### ISSUE TITLE
Виконання лабораторної роботи №1

### ISSUE THREAD

**Issue by NCJavaCode** [ivaniukihornik/Repository_for_test_1#4]
Добрий день. 
Стовріть новий репозиторій і виконайте ЛР №1.

**Comment by ivaniukihornik** [comment]
Завдання з ЛР1 - тут: https://github.com/ivaniukihornik/Multiplication_table_test
Практичне завдання з КР - тут: https://github.com/ivaniukihornik/Repository_for_test_1

**Comment by NCJavaCode** [comment]
Прийнято!
